name: e2e
on:
  pull_request:
  push:
    branches:
      - master # Triggers on master to save the initial "base" snapshots
jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      checks: write
    environment: prod
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Install dependencies & build
        run: |
          npm ci
          npm run dist

      - name: Setup Mock Snapshots
        run: |
          mkdir -p /tmp/mock-snapshots/acceptance

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Running on PR: using current branch mock snapshot"
            cp src/util/__fixtures__/imgs/current/acceptance/test.png /tmp/mock-snapshots/
          else
            echo "Running on push/master: using base branch mock snapshot"
            cp src/util/__fixtures__/imgs/base/acceptance/test.png /tmp/mock-snapshots/
          fi

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_SCREENSHOT }}

      - name: Run Visual Snapshot Action
        id: visual-snapshots-diff
        uses: ./
        with:
          storage-prefix: 's3://linz-basemaps-screenshot'
          storage-url: 'https://d25mfjh9syaxsr.cloudfront.net'
